### ISSUE TITLE
more simple init with custom named queue

### ISSUE THREAD

**Issue by 1ternal** [fredwu/opq#1]
any thought about the more simple way like this? 
```elixir
{:ok, _} = OPQ.init(name: :items)

OPQ.enqueue(:items, fn -> IO.inspect("hello") end)
OPQ.enqueue(:items, fn -> IO.inspect("world") end)
```

**Comment by fredwu** [comment]
Good question, let me think about it. At the moment the `pid` you get back from the `init/1` is the pid of the feeder, not the queue itself, but that could potentially be changed.
