### ISSUE TITLE
update Genstage Dependency

### ISSUE THREAD

**Issue by ringofhealth** [fredwu/opq#8]
Awesome Library!

Genstage 1.0 has been released by the core team. 

https://github.com/elixir-lang/gen_stage/blob/master/CHANGELOG.md

currently using opq/crawler is incompatible will latest broadway 0.6.x, unless you override the dependency.

**Comment by fredwu** [comment]
Hi @ringofhealth, thanks for the heads up. Given I'm not actively maintaining the library, I wouldn't mind a PR for this if you're up for it. :)

**Comment by ringofhealth** [comment]
its a pretty straight forward change! send you a PR =)

**Comment by fredwu** [comment]
Thank you, merged! ❤️
